### ISSUE TITLE
RN314 support 

### ISSUE THREAD

**Issue by psyrykh** [fmor/rndu4000#1]
Hey, @fmor!

The job you've done looks awesome! I am looking for a custom installation of Debian on my RN314. Your kernel module works great! Well Done! The only thing need to be changed is a DeviceID to `3a18`.
```
00:1f.0 ISA bridge [0601]: Intel Corporation 82801JIB (ICH10) LPC Interface Controller [8086:3a18]
        Subsystem: Intel Corporation 82801JIB (ICH10) LPC Interface Controller [8086:3a18]
        Control: I/O+ Mem+ BusMaster+ SpecCycle- MemWINV- VGASnoop- ParErr- Stepping- SERR- FastB2B- DisINTx-
        Status: Cap+ 66MHz- UDF- FastB2B- ParErr- DEVSEL=medium >TAbort- <TAbort- <MAbort- >SERR- <PERR- INTx-
        Latency: 0
        Capabilities: <access denied>
        Kernel driver in use: lpc_ich
```  

Thanks a lot!
Pavlo.

P.S. sorry for opening an issue - I didn't find a better way to contact you.

**Comment by fmor** [comment]
Hi, i am glad to read your message. I will update the README to help others users with RN314. Thanks for reporting me.

**Comment by fmor** [comment]
I have a modified README  to commit. Can i add a link to your repo https://github.com/psyrykh/readynas-rn314 and cite your name ?

**Comment by psyrykh** [comment]
Sure, @fmor ! Thank you!
